#include <iostream>
#include <iomanip>
#include <sstream>
#include <cstring>
#include <openssl/sha.h>

using namespace std;

// Function to calculate SHA-256 hash value
string getSHA(string input) {
    unsigned char hash[SHA256_DIGEST_LENGTH];
    SHA256_CTX sha256;
    SHA256_Init(&sha256);
    SHA256_Update(&sha256, input.c_str(), input.length());
    SHA256_Final(hash, &sha256);
    
    stringstream ss;
    for (int i = 0; i < SHA256_DIGEST_LENGTH; i++) {
        ss << hex << setw(2) << setfill('0') << (int)hash[i];
    }
    
    return ss.str();
}

// Driver code
int main() {
    try {
        cout << "HashCode Generated by SHA-256 for:\n";

        string s1 = "Hello";
        cout << "\n" << s1 << " : " << getSHA(s1) << endl;

        string s2 = "OpenSSL";
        cout << "\n" << s2 << " : " << getSHA(s2) << endl;

        string s3 = "Algorithms"; 
        cout << "\n" << s3 << " : " << getSHA(s3) << endl;
    } catch (...) {
        cout << "Exception thrown\n";
    }
    
    return 0;
}
